package main

import (
	"fmt"
	"go/ast"
	"go/constant"
	"go/parser"
	"go/token"
	"go/types"
	"log"
	"os"
	"os/exec"
	"reflect"
	"strings"
	"unicode"

	pr "github.com/benoitkugler/webrender/css/properties"
)

// Code generator for CSS properties

func main() {
	propertiesFile := "properties_src.go"
	keywordsFile := "keywords_src.go"
	propertiesConsts, err := parseSourceCode(propertiesFile)
	if err != nil {
		log.Fatal(err)
	}
	keywordsConsts, err := parseSourceCode(keywordsFile)
	if err != nil {
		log.Fatal(err)
	}

	const OUT1 = "properties_gen.go"
	const OUT2 = "../../html/tree/accessors_gen.go"
	const OUT3 = "keywords_gen.go"

	err = generateProperties(propertiesConsts, OUT1, OUT2)
	if err != nil {
		log.Fatal(err)
	}
	err = generateKeywords(keywordsConsts, OUT3)

	fmt.Println("Generated", OUT1, OUT2, OUT3)
}

type constD struct {
	name  string
	value int
}

// returns the const Names, ignoring "_" identifier or non exported symbols
func parseConsts(specs []ast.Spec, info *types.Info) []constD {
	var out []constD
	for _, spec := range specs {
		value := spec.(*ast.ValueSpec)
		if len(value.Names) != 1 {
			log.Fatal("number of ident per file not supported in ast.Spec", value)
		}
		ident := value.Names[0]
		if ident.Name == "_" || !ident.IsExported() {
			continue
		}

		val := info.Defs[ident].(*types.Const)
		v, ok := constant.Int64Val(val.Val())
		if !ok {
			log.Fatal("unexpected constant", ident)
		}
		out = append(out, constD{ident.Name, int(v)})
	}
	return out
}

// we assume there is one and only one "iota" const definition
func parseSourceCode(sourceFile string) ([]constD, error) {
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, sourceFile, nil, parser.ParseComments|parser.DeclarationErrors)
	if err != nil {
		return nil, err
	}
	info := types.Info{Defs: make(map[*ast.Ident]types.Object)}
	_, err = (&types.Config{}).Check(sourceFile, fset, []*ast.File{f}, &info)
	if err != nil {
		return nil, err
	}
	for _, decl := range f.Decls {
		if gen, ok := decl.(*ast.GenDecl); ok && gen.Tok == token.CONST {
			return parseConsts(gen.Specs, &info), nil
		}
	}

	panic("missing consts in file " + sourceFile)
}

func kebabCase(s string) string {
	var out strings.Builder
	for i, r := range s {
		if i != 0 && unicode.IsUpper(r) {
			out.WriteRune('-')
		}
		out.WriteRune(unicode.ToLower(r))
	}
	return out.String()
}

// kebab case
func propertyCSSName(goPropName string) string {
	if goPropName[0] != 'P' {
		log.Fatal("unexpected prop name")
	}

	// remove the "P" prefix and convert the case
	return kebabCase(goPropName[1:])
}

func propertyTypeName(prop int) string {
	v := pr.InitialValues[pr.KnownProp(prop)]
	// special case for interface values
	if isImage(v) {
		return "Image"
	}
	return reflect.TypeOf(v).Name()
}

func isImage(v any) bool {
	interfaceType := reflect.TypeFor[pr.Image]()
	return reflect.TypeOf(v).Implements(interfaceType)
}

func generateProperties(props []constD, OUT1, OUT2 string) error {
	code1 := `package properties 
    
	// Code generated by properties/cmd/main.go from properties/properties_src.go DO NOT EDIT

	`
	code2 := `package tree 

	// Code generated by properties/cmd/main.go from properties/properties_src.go DO NOT EDIT

	import pr "github.com/benoitkugler/webrender/css/properties"
	
	`

	code_ITF := "type StyleAccessor interface {"

	codeStrings := `var propsNames = [...]string{
	`

	codeStringsRev := `
	// PropsFromNames maps CSS property names to internal enum tags.
	var PropsFromNames = map[string]KnownProp{
	`

	// sort.Slice(props, func(i, j int) bool { return props[i].propName < props[j].propName })

	const templateImpl = `
	func (s *%[1]s) Get%[2]s() %[3]s { return s.Get(pr.%[4]s.Key()).(%[3]s) }
	func (s *%[1]s) Set%[2]s(v %[3]s) { s.propsCache.setKnown(pr.%[4]s, v) }
	`

	for _, item := range props {
		varName := item.name
		camelName := item.name[1:]
		cssName := propertyCSSName(item.name)
		typeName := propertyTypeName(item.value)

		code1 += fmt.Sprintf(`
		func (s Properties) Get%[1]s() %[2]s { return s[%[3]s].(%[2]s)	}
		func (s Properties) Set%[1]s(v %[2]s) { s[%[3]s] = v }
	
		`, camelName, typeName, varName)

		code2 += fmt.Sprintf(templateImpl, "ComputedStyle", camelName, "pr."+typeName, varName)
		code2 += fmt.Sprintf(templateImpl, "AnonymousStyle", camelName, "pr."+typeName, varName)

		code_ITF += fmt.Sprintf(`
    	Get%[1]s() %[2]s 
    	Set%[1]s(v %[2]s)
		`, camelName, typeName)

		codeStrings += fmt.Sprintf("%s: %q,\n", varName, cssName)
		codeStringsRev += fmt.Sprintf("%q: %s,\n", cssName, varName)
	}

	code_ITF += "}\n"
	codeStrings += "}\n"
	codeStringsRev += "}\n"

	if err := os.WriteFile(OUT1, []byte(code1+code_ITF+codeStrings+codeStringsRev), os.ModePerm); err != nil {
		return err
	}
	if err := os.WriteFile(OUT2, []byte(code2), os.ModePerm); err != nil {
		return err
	}

	if err := exec.Command("goimports", "-w", OUT1).Run(); err != nil {
		return err
	}
	if err := exec.Command("goimports", "-w", OUT2).Run(); err != nil {
		return err
	}

	return nil
}

func generateKeywords(keywords []constD, OUT3 string) error {
	var casesParse, casesStringify []string
	for _, v := range keywords {
		cssName := kebabCase(v.name)
		casesParse = append(casesParse, fmt.Sprintf("case %q: return %s", cssName, v.name))
		casesStringify = append(casesStringify, fmt.Sprintf("case %s: return %q", v.name, cssName))
	}

	code := fmt.Sprintf(`package properties

	// Code generated by properties/cmd/main.go from properties/keywords_src.go DO NOT EDIT
	
	func NewKeyword(s string) Keyword {
		switch s {
			%s
			default:
				return 0
		}
	}

	func (t Keyword) String() string {
		switch t {
			%s
			default: 
				return fmt.Sprintf("unknown keyword %%d", t)
		}
	}
	`, strings.Join(casesParse, "\n"), strings.Join(casesStringify, "\n"))

	if err := os.WriteFile(OUT3, []byte(code), os.ModePerm); err != nil {
		return (err)
	}

	if err := exec.Command("goimports", "-w", OUT3).Run(); err != nil {
		return (err)
	}

	return nil
}
