package keywords

import (
	"fmt"
	"os"
	"sort"
	"strings"
	"testing"

	"github.com/benoitkugler/webrender/utils"
)

// return the (non qualified) const name used to encode [s]
func constName(s string) string {
	parts := strings.Split(s, "-")
	for i, p := range parts {
		parts[i] = strings.Title(p)
	}
	return strings.Join(parts, "")
}

func TestGenKeywordsParser(t *testing.T) {
	// t.Skip("dev only test")
	l := [...]string{
		"center", "space-between", "space-around", "space-evenly",
		"stretch", "normal", "flex-start", "flex-end",
		"start", "end", "left", "right",
		"safe", "unsafe",
		"center", "start", "end", "flex-start", "flex-end", "left",
		"right",
		"normal", "stretch", "center", "start", "end", "self-start",
		"self-end", "flex-start", "flex-end", "left", "right",
		"legacy",
		"baseline",
		"center", "start", "end", "self-start", "self-end",
		"flex-start", "flex-end", "left", "right",
		"auto", "normal", "stretch", "center", "start", "end",
		"self-start", "self-end", "flex-start", "flex-end", "left",
		"right",
		"center", "start", "end", "self-start", "self-end",
		"flex-start", "flex-end", "left", "right",
		"normal", "stretch", "center", "start", "end", "self-start",
		"self-end", "flex-start", "flex-end",
		"baseline",
		"center", "start", "end", "self-start", "self-end",
		"flex-start", "flex-end",
		"auto", "normal", "stretch", "center", "start", "end",
		"self-start", "self-end", "flex-start", "flex-end",
		"center", "start", "end", "self-start", "self-end",
		"flex-start", "flex-end",
		"center", "space-between", "space-around", "space-evenly",
		"stretch", "normal", "flex-start", "flex-end",
		"start", "end",
		"baseline",
		"center", "start", "end", "flex-start", "flex-end",
		"first", "last",
		"none", "table-caption", "table-row-group", "table-cell",
		"table-header-group", "table-footer-group", "table-row",
		"table-column-group", "table-column",
		"inline-table", "inline-flex", "inline-grid",
		"inline-block", "inline", "flow-root",
		"table", "flex", "grid",
		"block", "flow", "list-item",
	}

	m := utils.NewSet(l[:]...)
	var out []string
	for l := range m {
		out = append(out, l)
	}
	sort.Strings(out)

	consts, cases1, cases2 := make([]string, len(out)), make([]string, len(out)), make([]string, len(out))
	for i, s := range out {
		name := constName(s)
		consts[i] = name
		cases1[i] = fmt.Sprintf("case %q:\nreturn %s", s, name)
		cases2[i] = fmt.Sprintf("case %s:\nreturn %q", name, s)
	}

	code := fmt.Sprintf(`
	package keywords

	// Code generated by keywords_test.go. DO NOT EDIT

	import "fmt"

	// Keyword efficiently stores CSS keywords
	type Keyword uint8

	const (
		_ Keyword = iota 
		%s
	)
	
	func New(s string) Keyword {
		switch s {
			%s
			default:
				return 0
		}
	}
		
	func (kw Keyword) String() string {
		switch kw {
			%s 
			default:
				return fmt.Sprintf("<unknown keyword %%d>", kw)
		}
	}
		`, strings.Join(consts, "\n"), strings.Join(cases1, "\n"), strings.Join(cases2, "\n"),
	)

	os.WriteFile("keywords.go", []byte(code), os.ModePerm)
}
