
	package keywords

	// Code generated by keywords_test.go. DO NOT EDIT

	import "fmt"

	// Keyword efficiently stores CSS keywords
	type Keyword uint8

	const (
		_ Keyword = iota 
		Auto
Baseline
Block
Center
End
First
Flex
FlexEnd
FlexStart
Flow
FlowRoot
Grid
Inline
InlineBlock
InlineFlex
InlineGrid
InlineTable
Last
Left
Legacy
ListItem
None
Normal
Right
Safe
SelfEnd
SelfStart
SpaceAround
SpaceBetween
SpaceEvenly
Start
Stretch
Table
TableCaption
TableCell
TableColumn
TableColumnGroup
TableFooterGroup
TableHeaderGroup
TableRow
TableRowGroup
Unsafe
	)
	
	func New(s string) Keyword {
		switch s {
			case "auto":
return Auto
case "baseline":
return Baseline
case "block":
return Block
case "center":
return Center
case "end":
return End
case "first":
return First
case "flex":
return Flex
case "flex-end":
return FlexEnd
case "flex-start":
return FlexStart
case "flow":
return Flow
case "flow-root":
return FlowRoot
case "grid":
return Grid
case "inline":
return Inline
case "inline-block":
return InlineBlock
case "inline-flex":
return InlineFlex
case "inline-grid":
return InlineGrid
case "inline-table":
return InlineTable
case "last":
return Last
case "left":
return Left
case "legacy":
return Legacy
case "list-item":
return ListItem
case "none":
return None
case "normal":
return Normal
case "right":
return Right
case "safe":
return Safe
case "self-end":
return SelfEnd
case "self-start":
return SelfStart
case "space-around":
return SpaceAround
case "space-between":
return SpaceBetween
case "space-evenly":
return SpaceEvenly
case "start":
return Start
case "stretch":
return Stretch
case "table":
return Table
case "table-caption":
return TableCaption
case "table-cell":
return TableCell
case "table-column":
return TableColumn
case "table-column-group":
return TableColumnGroup
case "table-footer-group":
return TableFooterGroup
case "table-header-group":
return TableHeaderGroup
case "table-row":
return TableRow
case "table-row-group":
return TableRowGroup
case "unsafe":
return Unsafe
			default:
				return 0
		}
	}
		
	func (kw Keyword) String() string {
		switch kw {
			case Auto:
return "auto"
case Baseline:
return "baseline"
case Block:
return "block"
case Center:
return "center"
case End:
return "end"
case First:
return "first"
case Flex:
return "flex"
case FlexEnd:
return "flex-end"
case FlexStart:
return "flex-start"
case Flow:
return "flow"
case FlowRoot:
return "flow-root"
case Grid:
return "grid"
case Inline:
return "inline"
case InlineBlock:
return "inline-block"
case InlineFlex:
return "inline-flex"
case InlineGrid:
return "inline-grid"
case InlineTable:
return "inline-table"
case Last:
return "last"
case Left:
return "left"
case Legacy:
return "legacy"
case ListItem:
return "list-item"
case None:
return "none"
case Normal:
return "normal"
case Right:
return "right"
case Safe:
return "safe"
case SelfEnd:
return "self-end"
case SelfStart:
return "self-start"
case SpaceAround:
return "space-around"
case SpaceBetween:
return "space-between"
case SpaceEvenly:
return "space-evenly"
case Start:
return "start"
case Stretch:
return "stretch"
case Table:
return "table"
case TableCaption:
return "table-caption"
case TableCell:
return "table-cell"
case TableColumn:
return "table-column"
case TableColumnGroup:
return "table-column-group"
case TableFooterGroup:
return "table-footer-group"
case TableHeaderGroup:
return "table-header-group"
case TableRow:
return "table-row"
case TableRowGroup:
return "table-row-group"
case Unsafe:
return "unsafe" 
			default:
				return fmt.Sprintf("<unknown keyword %d>", kw)
		}
	}
		