package properties

// Code generated by properties/cmd/main.go from properties/properties_src.go DO NOT EDIT

func (s Properties) GetBorderBottomColor() Color  { return s[PBorderBottomColor].(Color) }
func (s Properties) SetBorderBottomColor(v Color) { s[PBorderBottomColor] = v }

func (s Properties) GetBorderBottomStyle() String  { return s[PBorderBottomStyle].(String) }
func (s Properties) SetBorderBottomStyle(v String) { s[PBorderBottomStyle] = v }

func (s Properties) GetBorderBottomWidth() TaggedDim  { return s[PBorderBottomWidth].(TaggedDim) }
func (s Properties) SetBorderBottomWidth(v TaggedDim) { s[PBorderBottomWidth] = v }

func (s Properties) GetMarginBottom() TaggedDim  { return s[PMarginBottom].(TaggedDim) }
func (s Properties) SetMarginBottom(v TaggedDim) { s[PMarginBottom] = v }

func (s Properties) GetPaddingBottom() TaggedDim  { return s[PPaddingBottom].(TaggedDim) }
func (s Properties) SetPaddingBottom(v TaggedDim) { s[PPaddingBottom] = v }

func (s Properties) GetBorderLeftColor() Color  { return s[PBorderLeftColor].(Color) }
func (s Properties) SetBorderLeftColor(v Color) { s[PBorderLeftColor] = v }

func (s Properties) GetBorderLeftStyle() String  { return s[PBorderLeftStyle].(String) }
func (s Properties) SetBorderLeftStyle(v String) { s[PBorderLeftStyle] = v }

func (s Properties) GetBorderLeftWidth() TaggedDim  { return s[PBorderLeftWidth].(TaggedDim) }
func (s Properties) SetBorderLeftWidth(v TaggedDim) { s[PBorderLeftWidth] = v }

func (s Properties) GetMarginLeft() TaggedDim  { return s[PMarginLeft].(TaggedDim) }
func (s Properties) SetMarginLeft(v TaggedDim) { s[PMarginLeft] = v }

func (s Properties) GetPaddingLeft() TaggedDim  { return s[PPaddingLeft].(TaggedDim) }
func (s Properties) SetPaddingLeft(v TaggedDim) { s[PPaddingLeft] = v }

func (s Properties) GetBorderRightColor() Color  { return s[PBorderRightColor].(Color) }
func (s Properties) SetBorderRightColor(v Color) { s[PBorderRightColor] = v }

func (s Properties) GetBorderRightStyle() String  { return s[PBorderRightStyle].(String) }
func (s Properties) SetBorderRightStyle(v String) { s[PBorderRightStyle] = v }

func (s Properties) GetBorderRightWidth() TaggedDim  { return s[PBorderRightWidth].(TaggedDim) }
func (s Properties) SetBorderRightWidth(v TaggedDim) { s[PBorderRightWidth] = v }

func (s Properties) GetMarginRight() TaggedDim  { return s[PMarginRight].(TaggedDim) }
func (s Properties) SetMarginRight(v TaggedDim) { s[PMarginRight] = v }

func (s Properties) GetPaddingRight() TaggedDim  { return s[PPaddingRight].(TaggedDim) }
func (s Properties) SetPaddingRight(v TaggedDim) { s[PPaddingRight] = v }

func (s Properties) GetBorderTopColor() Color  { return s[PBorderTopColor].(Color) }
func (s Properties) SetBorderTopColor(v Color) { s[PBorderTopColor] = v }

func (s Properties) GetBorderTopStyle() String  { return s[PBorderTopStyle].(String) }
func (s Properties) SetBorderTopStyle(v String) { s[PBorderTopStyle] = v }

func (s Properties) GetBorderTopWidth() TaggedDim  { return s[PBorderTopWidth].(TaggedDim) }
func (s Properties) SetBorderTopWidth(v TaggedDim) { s[PBorderTopWidth] = v }

func (s Properties) GetMarginTop() TaggedDim  { return s[PMarginTop].(TaggedDim) }
func (s Properties) SetMarginTop(v TaggedDim) { s[PMarginTop] = v }

func (s Properties) GetPaddingTop() TaggedDim  { return s[PPaddingTop].(TaggedDim) }
func (s Properties) SetPaddingTop(v TaggedDim) { s[PPaddingTop] = v }

func (s Properties) GetWidth() TaggedDim  { return s[PWidth].(TaggedDim) }
func (s Properties) SetWidth(v TaggedDim) { s[PWidth] = v }

func (s Properties) GetHeight() TaggedDim  { return s[PHeight].(TaggedDim) }
func (s Properties) SetHeight(v TaggedDim) { s[PHeight] = v }

func (s Properties) GetMinWidth() TaggedDim  { return s[PMinWidth].(TaggedDim) }
func (s Properties) SetMinWidth(v TaggedDim) { s[PMinWidth] = v }

func (s Properties) GetMinHeight() TaggedDim  { return s[PMinHeight].(TaggedDim) }
func (s Properties) SetMinHeight(v TaggedDim) { s[PMinHeight] = v }

func (s Properties) GetMaxWidth() TaggedDim  { return s[PMaxWidth].(TaggedDim) }
func (s Properties) SetMaxWidth(v TaggedDim) { s[PMaxWidth] = v }

func (s Properties) GetMaxHeight() TaggedDim  { return s[PMaxHeight].(TaggedDim) }
func (s Properties) SetMaxHeight(v TaggedDim) { s[PMaxHeight] = v }

func (s Properties) GetBorderCollapse() String  { return s[PBorderCollapse].(String) }
func (s Properties) SetBorderCollapse(v String) { s[PBorderCollapse] = v }

func (s Properties) GetTabSize() TaggedDim  { return s[PTabSize].(TaggedDim) }
func (s Properties) SetTabSize(v TaggedDim) { s[PTabSize] = v }

func (s Properties) GetBorderImageSource() Image  { return s[PBorderImageSource].(Image) }
func (s Properties) SetBorderImageSource(v Image) { s[PBorderImageSource] = v }

func (s Properties) GetMaskBorderSource() Image  { return s[PMaskBorderSource].(Image) }
func (s Properties) SetMaskBorderSource(v Image) { s[PMaskBorderSource] = v }

func (s Properties) GetColor() Color  { return s[PColor].(Color) }
func (s Properties) SetColor(v Color) { s[PColor] = v }

func (s Properties) GetDirection() Keyword  { return s[PDirection].(Keyword) }
func (s Properties) SetDirection(v Keyword) { s[PDirection] = v }

func (s Properties) GetDisplay() Display  { return s[PDisplay].(Display) }
func (s Properties) SetDisplay(v Display) { s[PDisplay] = v }

func (s Properties) GetFloat() String  { return s[PFloat].(String) }
func (s Properties) SetFloat(v String) { s[PFloat] = v }

func (s Properties) GetLineHeight() TaggedDim  { return s[PLineHeight].(TaggedDim) }
func (s Properties) SetLineHeight(v TaggedDim) { s[PLineHeight] = v }

func (s Properties) GetPosition() BoolString  { return s[PPosition].(BoolString) }
func (s Properties) SetPosition(v BoolString) { s[PPosition] = v }

func (s Properties) GetTableLayout() String  { return s[PTableLayout].(String) }
func (s Properties) SetTableLayout(v String) { s[PTableLayout] = v }

func (s Properties) GetTop() TaggedDim  { return s[PTop].(TaggedDim) }
func (s Properties) SetTop(v TaggedDim) { s[PTop] = v }

func (s Properties) GetVerticalAlign() TaggedDim  { return s[PVerticalAlign].(TaggedDim) }
func (s Properties) SetVerticalAlign(v TaggedDim) { s[PVerticalAlign] = v }

func (s Properties) GetVisibility() String  { return s[PVisibility].(String) }
func (s Properties) SetVisibility(v String) { s[PVisibility] = v }

func (s Properties) GetBorderBottomLeftRadius() Point  { return s[PBorderBottomLeftRadius].(Point) }
func (s Properties) SetBorderBottomLeftRadius(v Point) { s[PBorderBottomLeftRadius] = v }

func (s Properties) GetBorderBottomRightRadius() Point  { return s[PBorderBottomRightRadius].(Point) }
func (s Properties) SetBorderBottomRightRadius(v Point) { s[PBorderBottomRightRadius] = v }

func (s Properties) GetBorderTopLeftRadius() Point  { return s[PBorderTopLeftRadius].(Point) }
func (s Properties) SetBorderTopLeftRadius(v Point) { s[PBorderTopLeftRadius] = v }

func (s Properties) GetBorderTopRightRadius() Point  { return s[PBorderTopRightRadius].(Point) }
func (s Properties) SetBorderTopRightRadius(v Point) { s[PBorderTopRightRadius] = v }

func (s Properties) GetColumnCount() IntString  { return s[PColumnCount].(IntString) }
func (s Properties) SetColumnCount(v IntString) { s[PColumnCount] = v }

func (s Properties) GetColumnWidth() TaggedDim  { return s[PColumnWidth].(TaggedDim) }
func (s Properties) SetColumnWidth(v TaggedDim) { s[PColumnWidth] = v }

func (s Properties) GetFontFamily() Strings  { return s[PFontFamily].(Strings) }
func (s Properties) SetFontFamily(v Strings) { s[PFontFamily] = v }

func (s Properties) GetFontFeatureSettings() FontFeatures {
	return s[PFontFeatureSettings].(FontFeatures)
}
func (s Properties) SetFontFeatureSettings(v FontFeatures) { s[PFontFeatureSettings] = v }

func (s Properties) GetFontKerning() String  { return s[PFontKerning].(String) }
func (s Properties) SetFontKerning(v String) { s[PFontKerning] = v }

func (s Properties) GetFontLanguageOverride() String  { return s[PFontLanguageOverride].(String) }
func (s Properties) SetFontLanguageOverride(v String) { s[PFontLanguageOverride] = v }

func (s Properties) GetFontSize() TaggedDim  { return s[PFontSize].(TaggedDim) }
func (s Properties) SetFontSize(v TaggedDim) { s[PFontSize] = v }

func (s Properties) GetFontStretch() String  { return s[PFontStretch].(String) }
func (s Properties) SetFontStretch(v String) { s[PFontStretch] = v }

func (s Properties) GetFontStyle() String  { return s[PFontStyle].(String) }
func (s Properties) SetFontStyle(v String) { s[PFontStyle] = v }

func (s Properties) GetFontVariantAlternates() String  { return s[PFontVariantAlternates].(String) }
func (s Properties) SetFontVariantAlternates(v String) { s[PFontVariantAlternates] = v }

func (s Properties) GetFontVariantCaps() String  { return s[PFontVariantCaps].(String) }
func (s Properties) SetFontVariantCaps(v String) { s[PFontVariantCaps] = v }

func (s Properties) GetFontVariantEastAsian() SStrings  { return s[PFontVariantEastAsian].(SStrings) }
func (s Properties) SetFontVariantEastAsian(v SStrings) { s[PFontVariantEastAsian] = v }

func (s Properties) GetFontVariantLigatures() SStrings  { return s[PFontVariantLigatures].(SStrings) }
func (s Properties) SetFontVariantLigatures(v SStrings) { s[PFontVariantLigatures] = v }

func (s Properties) GetFontVariantNumeric() SStrings  { return s[PFontVariantNumeric].(SStrings) }
func (s Properties) SetFontVariantNumeric(v SStrings) { s[PFontVariantNumeric] = v }

func (s Properties) GetFontVariantPosition() String  { return s[PFontVariantPosition].(String) }
func (s Properties) SetFontVariantPosition(v String) { s[PFontVariantPosition] = v }

func (s Properties) GetFontWeight() IntString  { return s[PFontWeight].(IntString) }
func (s Properties) SetFontWeight(v IntString) { s[PFontWeight] = v }

func (s Properties) GetFontVariationSettings() SFloatStrings {
	return s[PFontVariationSettings].(SFloatStrings)
}
func (s Properties) SetFontVariationSettings(v SFloatStrings) { s[PFontVariationSettings] = v }

func (s Properties) GetHyphenateLimitZone() TaggedDim  { return s[PHyphenateLimitZone].(TaggedDim) }
func (s Properties) SetHyphenateLimitZone(v TaggedDim) { s[PHyphenateLimitZone] = v }

func (s Properties) GetHyphenateCharacter() String  { return s[PHyphenateCharacter].(String) }
func (s Properties) SetHyphenateCharacter(v String) { s[PHyphenateCharacter] = v }

func (s Properties) GetHyphenateLimitChars() Limits  { return s[PHyphenateLimitChars].(Limits) }
func (s Properties) SetHyphenateLimitChars(v Limits) { s[PHyphenateLimitChars] = v }

func (s Properties) GetHyphens() String  { return s[PHyphens].(String) }
func (s Properties) SetHyphens(v String) { s[PHyphens] = v }

func (s Properties) GetLetterSpacing() TaggedDim  { return s[PLetterSpacing].(TaggedDim) }
func (s Properties) SetLetterSpacing(v TaggedDim) { s[PLetterSpacing] = v }

func (s Properties) GetTextAlignAll() String  { return s[PTextAlignAll].(String) }
func (s Properties) SetTextAlignAll(v String) { s[PTextAlignAll] = v }

func (s Properties) GetTextAlignLast() String  { return s[PTextAlignLast].(String) }
func (s Properties) SetTextAlignLast(v String) { s[PTextAlignLast] = v }

func (s Properties) GetTextIndent() TaggedDim  { return s[PTextIndent].(TaggedDim) }
func (s Properties) SetTextIndent(v TaggedDim) { s[PTextIndent] = v }

func (s Properties) GetTextTransform() String  { return s[PTextTransform].(String) }
func (s Properties) SetTextTransform(v String) { s[PTextTransform] = v }

func (s Properties) GetWhiteSpace() String  { return s[PWhiteSpace].(String) }
func (s Properties) SetWhiteSpace(v String) { s[PWhiteSpace] = v }

func (s Properties) GetWordBreak() String  { return s[PWordBreak].(String) }
func (s Properties) SetWordBreak(v String) { s[PWordBreak] = v }

func (s Properties) GetWordSpacing() TaggedDim  { return s[PWordSpacing].(TaggedDim) }
func (s Properties) SetWordSpacing(v TaggedDim) { s[PWordSpacing] = v }

func (s Properties) GetTransform() Transforms  { return s[PTransform].(Transforms) }
func (s Properties) SetTransform(v Transforms) { s[PTransform] = v }

func (s Properties) GetContinue() String  { return s[PContinue].(String) }
func (s Properties) SetContinue(v String) { s[PContinue] = v }

func (s Properties) GetMaxLines() TaggedInt  { return s[PMaxLines].(TaggedInt) }
func (s Properties) SetMaxLines(v TaggedInt) { s[PMaxLines] = v }

func (s Properties) GetOverflow() String  { return s[POverflow].(String) }
func (s Properties) SetOverflow(v String) { s[POverflow] = v }

func (s Properties) GetOverflowWrap() String  { return s[POverflowWrap].(String) }
func (s Properties) SetOverflowWrap(v String) { s[POverflowWrap] = v }

func (s Properties) GetCounterIncrement() SIntStrings  { return s[PCounterIncrement].(SIntStrings) }
func (s Properties) SetCounterIncrement(v SIntStrings) { s[PCounterIncrement] = v }

func (s Properties) GetCounterReset() SIntStrings  { return s[PCounterReset].(SIntStrings) }
func (s Properties) SetCounterReset(v SIntStrings) { s[PCounterReset] = v }

func (s Properties) GetCounterSet() SIntStrings  { return s[PCounterSet].(SIntStrings) }
func (s Properties) SetCounterSet(v SIntStrings) { s[PCounterSet] = v }

func (s Properties) GetAnchor() String  { return s[PAnchor].(String) }
func (s Properties) SetAnchor(v String) { s[PAnchor] = v }

func (s Properties) GetLink() TaggedString  { return s[PLink].(TaggedString) }
func (s Properties) SetLink(v TaggedString) { s[PLink] = v }

func (s Properties) GetLang() TaggedString  { return s[PLang].(TaggedString) }
func (s Properties) SetLang(v TaggedString) { s[PLang] = v }

func (s Properties) GetBoxDecorationBreak() String  { return s[PBoxDecorationBreak].(String) }
func (s Properties) SetBoxDecorationBreak(v String) { s[PBoxDecorationBreak] = v }

func (s Properties) GetBookmarkLabel() ContentProperties {
	return s[PBookmarkLabel].(ContentProperties)
}
func (s Properties) SetBookmarkLabel(v ContentProperties) { s[PBookmarkLabel] = v }

func (s Properties) GetBookmarkLevel() TaggedInt  { return s[PBookmarkLevel].(TaggedInt) }
func (s Properties) SetBookmarkLevel(v TaggedInt) { s[PBookmarkLevel] = v }

func (s Properties) GetBookmarkState() String  { return s[PBookmarkState].(String) }
func (s Properties) SetBookmarkState(v String) { s[PBookmarkState] = v }

func (s Properties) GetContent() SContent  { return s[PContent].(SContent) }
func (s Properties) SetContent(v SContent) { s[PContent] = v }

func (s Properties) GetStringSet() StringSet  { return s[PStringSet].(StringSet) }
func (s Properties) SetStringSet(v StringSet) { s[PStringSet] = v }

func (s Properties) GetImageOrientation() SBoolFloat  { return s[PImageOrientation].(SBoolFloat) }
func (s Properties) SetImageOrientation(v SBoolFloat) { s[PImageOrientation] = v }

func (s Properties) GetPage() Page  { return s[PPage].(Page) }
func (s Properties) SetPage(v Page) { s[PPage] = v }

func (s Properties) GetAppearance() String  { return s[PAppearance].(String) }
func (s Properties) SetAppearance(v String) { s[PAppearance] = v }

func (s Properties) GetOutlineColor() Color  { return s[POutlineColor].(Color) }
func (s Properties) SetOutlineColor(v Color) { s[POutlineColor] = v }

func (s Properties) GetOutlineStyle() String  { return s[POutlineStyle].(String) }
func (s Properties) SetOutlineStyle(v String) { s[POutlineStyle] = v }

func (s Properties) GetOutlineWidth() TaggedDim  { return s[POutlineWidth].(TaggedDim) }
func (s Properties) SetOutlineWidth(v TaggedDim) { s[POutlineWidth] = v }

func (s Properties) GetBoxSizing() String  { return s[PBoxSizing].(String) }
func (s Properties) SetBoxSizing(v String) { s[PBoxSizing] = v }

func (s Properties) GetBackgroundColor() Color  { return s[PBackgroundColor].(Color) }
func (s Properties) SetBackgroundColor(v Color) { s[PBackgroundColor] = v }

func (s Properties) GetBackgroundImage() Images  { return s[PBackgroundImage].(Images) }
func (s Properties) SetBackgroundImage(v Images) { s[PBackgroundImage] = v }

func (s Properties) GetBackgroundRepeat() Repeats  { return s[PBackgroundRepeat].(Repeats) }
func (s Properties) SetBackgroundRepeat(v Repeats) { s[PBackgroundRepeat] = v }

func (s Properties) GetBackgroundAttachment() Strings  { return s[PBackgroundAttachment].(Strings) }
func (s Properties) SetBackgroundAttachment(v Strings) { s[PBackgroundAttachment] = v }

func (s Properties) GetBackgroundPosition() Centers  { return s[PBackgroundPosition].(Centers) }
func (s Properties) SetBackgroundPosition(v Centers) { s[PBackgroundPosition] = v }

func (s Properties) GetBackgroundSize() Sizes  { return s[PBackgroundSize].(Sizes) }
func (s Properties) SetBackgroundSize(v Sizes) { s[PBackgroundSize] = v }

func (s Properties) GetBackgroundClip() Strings  { return s[PBackgroundClip].(Strings) }
func (s Properties) SetBackgroundClip(v Strings) { s[PBackgroundClip] = v }

func (s Properties) GetBackgroundOrigin() Strings  { return s[PBackgroundOrigin].(Strings) }
func (s Properties) SetBackgroundOrigin(v Strings) { s[PBackgroundOrigin] = v }

func (s Properties) GetBreakAfter() String  { return s[PBreakAfter].(String) }
func (s Properties) SetBreakAfter(v String) { s[PBreakAfter] = v }

func (s Properties) GetBreakBefore() String  { return s[PBreakBefore].(String) }
func (s Properties) SetBreakBefore(v String) { s[PBreakBefore] = v }

func (s Properties) GetBreakInside() String  { return s[PBreakInside].(String) }
func (s Properties) SetBreakInside(v String) { s[PBreakInside] = v }

func (s Properties) GetTextDecorationLine() Decorations  { return s[PTextDecorationLine].(Decorations) }
func (s Properties) SetTextDecorationLine(v Decorations) { s[PTextDecorationLine] = v }

func (s Properties) GetTextDecorationColor() Color  { return s[PTextDecorationColor].(Color) }
func (s Properties) SetTextDecorationColor(v Color) { s[PTextDecorationColor] = v }

func (s Properties) GetTextDecorationStyle() String  { return s[PTextDecorationStyle].(String) }
func (s Properties) SetTextDecorationStyle(v String) { s[PTextDecorationStyle] = v }

func (s Properties) GetTextDecorationThickness() TaggedDim {
	return s[PTextDecorationThickness].(TaggedDim)
}
func (s Properties) SetTextDecorationThickness(v TaggedDim) { s[PTextDecorationThickness] = v }

func (s Properties) GetTextUnderlineOffset() TaggedDim  { return s[PTextUnderlineOffset].(TaggedDim) }
func (s Properties) SetTextUnderlineOffset(v TaggedDim) { s[PTextUnderlineOffset] = v }

func (s Properties) GetGridAutoColumns() GridAuto  { return s[PGridAutoColumns].(GridAuto) }
func (s Properties) SetGridAutoColumns(v GridAuto) { s[PGridAutoColumns] = v }

func (s Properties) GetGridAutoFlow() Strings  { return s[PGridAutoFlow].(Strings) }
func (s Properties) SetGridAutoFlow(v Strings) { s[PGridAutoFlow] = v }

func (s Properties) GetGridAutoRows() GridAuto  { return s[PGridAutoRows].(GridAuto) }
func (s Properties) SetGridAutoRows(v GridAuto) { s[PGridAutoRows] = v }

func (s Properties) GetGridTemplateColumns() GridTemplate {
	return s[PGridTemplateColumns].(GridTemplate)
}
func (s Properties) SetGridTemplateColumns(v GridTemplate) { s[PGridTemplateColumns] = v }

func (s Properties) GetGridTemplateRows() GridTemplate  { return s[PGridTemplateRows].(GridTemplate) }
func (s Properties) SetGridTemplateRows(v GridTemplate) { s[PGridTemplateRows] = v }

func (s Properties) GetGridTemplateAreas() GridTemplateAreas {
	return s[PGridTemplateAreas].(GridTemplateAreas)
}
func (s Properties) SetGridTemplateAreas(v GridTemplateAreas) { s[PGridTemplateAreas] = v }

func (s Properties) GetGridRowStart() GridLine  { return s[PGridRowStart].(GridLine) }
func (s Properties) SetGridRowStart(v GridLine) { s[PGridRowStart] = v }

func (s Properties) GetGridColumnStart() GridLine  { return s[PGridColumnStart].(GridLine) }
func (s Properties) SetGridColumnStart(v GridLine) { s[PGridColumnStart] = v }

func (s Properties) GetGridRowEnd() GridLine  { return s[PGridRowEnd].(GridLine) }
func (s Properties) SetGridRowEnd(v GridLine) { s[PGridRowEnd] = v }

func (s Properties) GetGridColumnEnd() GridLine  { return s[PGridColumnEnd].(GridLine) }
func (s Properties) SetGridColumnEnd(v GridLine) { s[PGridColumnEnd] = v }

func (s Properties) GetAlignContent() JustifyOrAlign  { return s[PAlignContent].(JustifyOrAlign) }
func (s Properties) SetAlignContent(v JustifyOrAlign) { s[PAlignContent] = v }

func (s Properties) GetAlignItems() JustifyOrAlign  { return s[PAlignItems].(JustifyOrAlign) }
func (s Properties) SetAlignItems(v JustifyOrAlign) { s[PAlignItems] = v }

func (s Properties) GetAlignSelf() JustifyOrAlign  { return s[PAlignSelf].(JustifyOrAlign) }
func (s Properties) SetAlignSelf(v JustifyOrAlign) { s[PAlignSelf] = v }

func (s Properties) GetFlexBasis() TaggedDim  { return s[PFlexBasis].(TaggedDim) }
func (s Properties) SetFlexBasis(v TaggedDim) { s[PFlexBasis] = v }

func (s Properties) GetFlexDirection() String  { return s[PFlexDirection].(String) }
func (s Properties) SetFlexDirection(v String) { s[PFlexDirection] = v }

func (s Properties) GetFlexGrow() Float  { return s[PFlexGrow].(Float) }
func (s Properties) SetFlexGrow(v Float) { s[PFlexGrow] = v }

func (s Properties) GetFlexShrink() Float  { return s[PFlexShrink].(Float) }
func (s Properties) SetFlexShrink(v Float) { s[PFlexShrink] = v }

func (s Properties) GetFlexWrap() String  { return s[PFlexWrap].(String) }
func (s Properties) SetFlexWrap(v String) { s[PFlexWrap] = v }

func (s Properties) GetJustifyContent() JustifyOrAlign  { return s[PJustifyContent].(JustifyOrAlign) }
func (s Properties) SetJustifyContent(v JustifyOrAlign) { s[PJustifyContent] = v }

func (s Properties) GetJustifyItems() JustifyOrAlign  { return s[PJustifyItems].(JustifyOrAlign) }
func (s Properties) SetJustifyItems(v JustifyOrAlign) { s[PJustifyItems] = v }

func (s Properties) GetJustifySelf() JustifyOrAlign  { return s[PJustifySelf].(JustifyOrAlign) }
func (s Properties) SetJustifySelf(v JustifyOrAlign) { s[PJustifySelf] = v }

func (s Properties) GetOrder() Int  { return s[POrder].(Int) }
func (s Properties) SetOrder(v Int) { s[POrder] = v }

func (s Properties) GetColumnGap() TaggedDim  { return s[PColumnGap].(TaggedDim) }
func (s Properties) SetColumnGap(v TaggedDim) { s[PColumnGap] = v }

func (s Properties) GetRowGap() TaggedDim  { return s[PRowGap].(TaggedDim) }
func (s Properties) SetRowGap(v TaggedDim) { s[PRowGap] = v }

func (s Properties) GetBottom() TaggedDim  { return s[PBottom].(TaggedDim) }
func (s Properties) SetBottom(v TaggedDim) { s[PBottom] = v }

func (s Properties) GetCaptionSide() String  { return s[PCaptionSide].(String) }
func (s Properties) SetCaptionSide(v String) { s[PCaptionSide] = v }

func (s Properties) GetClear() String  { return s[PClear].(String) }
func (s Properties) SetClear(v String) { s[PClear] = v }

func (s Properties) GetClip() Values  { return s[PClip].(Values) }
func (s Properties) SetClip(v Values) { s[PClip] = v }

func (s Properties) GetEmptyCells() String  { return s[PEmptyCells].(String) }
func (s Properties) SetEmptyCells(v String) { s[PEmptyCells] = v }

func (s Properties) GetLeft() TaggedDim  { return s[PLeft].(TaggedDim) }
func (s Properties) SetLeft(v TaggedDim) { s[PLeft] = v }

func (s Properties) GetRight() TaggedDim  { return s[PRight].(TaggedDim) }
func (s Properties) SetRight(v TaggedDim) { s[PRight] = v }

func (s Properties) GetListStyleImage() Image  { return s[PListStyleImage].(Image) }
func (s Properties) SetListStyleImage(v Image) { s[PListStyleImage] = v }

func (s Properties) GetListStylePosition() String  { return s[PListStylePosition].(String) }
func (s Properties) SetListStylePosition(v String) { s[PListStylePosition] = v }

func (s Properties) GetListStyleType() CounterStyleID  { return s[PListStyleType].(CounterStyleID) }
func (s Properties) SetListStyleType(v CounterStyleID) { s[PListStyleType] = v }

func (s Properties) GetTextOverflow() String  { return s[PTextOverflow].(String) }
func (s Properties) SetTextOverflow(v String) { s[PTextOverflow] = v }

func (s Properties) GetBlockEllipsis() TaggedString  { return s[PBlockEllipsis].(TaggedString) }
func (s Properties) SetBlockEllipsis(v TaggedString) { s[PBlockEllipsis] = v }

func (s Properties) GetBorderSpacing() Point  { return s[PBorderSpacing].(Point) }
func (s Properties) SetBorderSpacing(v Point) { s[PBorderSpacing] = v }

func (s Properties) GetTransformOrigin() Point  { return s[PTransformOrigin].(Point) }
func (s Properties) SetTransformOrigin(v Point) { s[PTransformOrigin] = v }

func (s Properties) GetFontVariant() String  { return s[PFontVariant].(String) }
func (s Properties) SetFontVariant(v String) { s[PFontVariant] = v }

func (s Properties) GetMarginBreak() String  { return s[PMarginBreak].(String) }
func (s Properties) SetMarginBreak(v String) { s[PMarginBreak] = v }

func (s Properties) GetOrphans() Int  { return s[POrphans].(Int) }
func (s Properties) SetOrphans(v Int) { s[POrphans] = v }

func (s Properties) GetWidows() Int  { return s[PWidows].(Int) }
func (s Properties) SetWidows(v Int) { s[PWidows] = v }

func (s Properties) GetFootnoteDisplay() String  { return s[PFootnoteDisplay].(String) }
func (s Properties) SetFootnoteDisplay(v String) { s[PFootnoteDisplay] = v }

func (s Properties) GetFootnotePolicy() String  { return s[PFootnotePolicy].(String) }
func (s Properties) SetFootnotePolicy(v String) { s[PFootnotePolicy] = v }

func (s Properties) GetQuotes() Quotes  { return s[PQuotes].(Quotes) }
func (s Properties) SetQuotes(v Quotes) { s[PQuotes] = v }

func (s Properties) GetImageResolution() TaggedDim  { return s[PImageResolution].(TaggedDim) }
func (s Properties) SetImageResolution(v TaggedDim) { s[PImageResolution] = v }

func (s Properties) GetImageRendering() String  { return s[PImageRendering].(String) }
func (s Properties) SetImageRendering(v String) { s[PImageRendering] = v }

func (s Properties) GetColumnFill() String  { return s[PColumnFill].(String) }
func (s Properties) SetColumnFill(v String) { s[PColumnFill] = v }

func (s Properties) GetColumnSpan() String  { return s[PColumnSpan].(String) }
func (s Properties) SetColumnSpan(v String) { s[PColumnSpan] = v }

func (s Properties) GetColumnRuleColor() Color  { return s[PColumnRuleColor].(Color) }
func (s Properties) SetColumnRuleColor(v Color) { s[PColumnRuleColor] = v }

func (s Properties) GetSize() Point  { return s[PSize].(Point) }
func (s Properties) SetSize(v Point) { s[PSize] = v }

func (s Properties) GetBleedLeft() TaggedDim  { return s[PBleedLeft].(TaggedDim) }
func (s Properties) SetBleedLeft(v TaggedDim) { s[PBleedLeft] = v }

func (s Properties) GetBleedRight() TaggedDim  { return s[PBleedRight].(TaggedDim) }
func (s Properties) SetBleedRight(v TaggedDim) { s[PBleedRight] = v }

func (s Properties) GetBleedTop() TaggedDim  { return s[PBleedTop].(TaggedDim) }
func (s Properties) SetBleedTop(v TaggedDim) { s[PBleedTop] = v }

func (s Properties) GetBleedBottom() TaggedDim  { return s[PBleedBottom].(TaggedDim) }
func (s Properties) SetBleedBottom(v TaggedDim) { s[PBleedBottom] = v }

func (s Properties) GetMarks() Marks  { return s[PMarks].(Marks) }
func (s Properties) SetMarks(v Marks) { s[PMarks] = v }

func (s Properties) GetUnicodeBidi() String  { return s[PUnicodeBidi].(String) }
func (s Properties) SetUnicodeBidi(v String) { s[PUnicodeBidi] = v }

func (s Properties) GetZIndex() IntString  { return s[PZIndex].(IntString) }
func (s Properties) SetZIndex(v IntString) { s[PZIndex] = v }

func (s Properties) GetOpacity() Float  { return s[POpacity].(Float) }
func (s Properties) SetOpacity(v Float) { s[POpacity] = v }

func (s Properties) GetColumnRuleStyle() String  { return s[PColumnRuleStyle].(String) }
func (s Properties) SetColumnRuleStyle(v String) { s[PColumnRuleStyle] = v }

func (s Properties) GetColumnRuleWidth() TaggedDim  { return s[PColumnRuleWidth].(TaggedDim) }
func (s Properties) SetColumnRuleWidth(v TaggedDim) { s[PColumnRuleWidth] = v }

func (s Properties) GetBorderImageSlice() Values  { return s[PBorderImageSlice].(Values) }
func (s Properties) SetBorderImageSlice(v Values) { s[PBorderImageSlice] = v }

func (s Properties) GetBorderImageWidth() Values  { return s[PBorderImageWidth].(Values) }
func (s Properties) SetBorderImageWidth(v Values) { s[PBorderImageWidth] = v }

func (s Properties) GetBorderImageOutset() Values  { return s[PBorderImageOutset].(Values) }
func (s Properties) SetBorderImageOutset(v Values) { s[PBorderImageOutset] = v }

func (s Properties) GetBorderImageRepeat() Strings  { return s[PBorderImageRepeat].(Strings) }
func (s Properties) SetBorderImageRepeat(v Strings) { s[PBorderImageRepeat] = v }

func (s Properties) GetMaskBorderSlice() Values  { return s[PMaskBorderSlice].(Values) }
func (s Properties) SetMaskBorderSlice(v Values) { s[PMaskBorderSlice] = v }

func (s Properties) GetMaskBorderWidth() Values  { return s[PMaskBorderWidth].(Values) }
func (s Properties) SetMaskBorderWidth(v Values) { s[PMaskBorderWidth] = v }

func (s Properties) GetMaskBorderOutset() Values  { return s[PMaskBorderOutset].(Values) }
func (s Properties) SetMaskBorderOutset(v Values) { s[PMaskBorderOutset] = v }

func (s Properties) GetMaskBorderRepeat() Strings  { return s[PMaskBorderRepeat].(Strings) }
func (s Properties) SetMaskBorderRepeat(v Strings) { s[PMaskBorderRepeat] = v }

func (s Properties) GetMaskBorderMode() String  { return s[PMaskBorderMode].(String) }
func (s Properties) SetMaskBorderMode(v String) { s[PMaskBorderMode] = v }

func (s Properties) GetObjectFit() String  { return s[PObjectFit].(String) }
func (s Properties) SetObjectFit(v String) { s[PObjectFit] = v }

func (s Properties) GetObjectPosition() CenterPos  { return s[PObjectPosition].(CenterPos) }
func (s Properties) SetObjectPosition(v CenterPos) { s[PObjectPosition] = v }

type StyleAccessor interface {
	GetBorderBottomColor() Color
	SetBorderBottomColor(v Color)

	GetBorderBottomStyle() String
	SetBorderBottomStyle(v String)

	GetBorderBottomWidth() TaggedDim
	SetBorderBottomWidth(v TaggedDim)

	GetMarginBottom() TaggedDim
	SetMarginBottom(v TaggedDim)

	GetPaddingBottom() TaggedDim
	SetPaddingBottom(v TaggedDim)

	GetBorderLeftColor() Color
	SetBorderLeftColor(v Color)

	GetBorderLeftStyle() String
	SetBorderLeftStyle(v String)

	GetBorderLeftWidth() TaggedDim
	SetBorderLeftWidth(v TaggedDim)

	GetMarginLeft() TaggedDim
	SetMarginLeft(v TaggedDim)

	GetPaddingLeft() TaggedDim
	SetPaddingLeft(v TaggedDim)

	GetBorderRightColor() Color
	SetBorderRightColor(v Color)

	GetBorderRightStyle() String
	SetBorderRightStyle(v String)

	GetBorderRightWidth() TaggedDim
	SetBorderRightWidth(v TaggedDim)

	GetMarginRight() TaggedDim
	SetMarginRight(v TaggedDim)

	GetPaddingRight() TaggedDim
	SetPaddingRight(v TaggedDim)

	GetBorderTopColor() Color
	SetBorderTopColor(v Color)

	GetBorderTopStyle() String
	SetBorderTopStyle(v String)

	GetBorderTopWidth() TaggedDim
	SetBorderTopWidth(v TaggedDim)

	GetMarginTop() TaggedDim
	SetMarginTop(v TaggedDim)

	GetPaddingTop() TaggedDim
	SetPaddingTop(v TaggedDim)

	GetWidth() TaggedDim
	SetWidth(v TaggedDim)

	GetHeight() TaggedDim
	SetHeight(v TaggedDim)

	GetMinWidth() TaggedDim
	SetMinWidth(v TaggedDim)

	GetMinHeight() TaggedDim
	SetMinHeight(v TaggedDim)

	GetMaxWidth() TaggedDim
	SetMaxWidth(v TaggedDim)

	GetMaxHeight() TaggedDim
	SetMaxHeight(v TaggedDim)

	GetBorderCollapse() String
	SetBorderCollapse(v String)

	GetTabSize() TaggedDim
	SetTabSize(v TaggedDim)

	GetBorderImageSource() Image
	SetBorderImageSource(v Image)

	GetMaskBorderSource() Image
	SetMaskBorderSource(v Image)

	GetColor() Color
	SetColor(v Color)

	GetDirection() Keyword
	SetDirection(v Keyword)

	GetDisplay() Display
	SetDisplay(v Display)

	GetFloat() String
	SetFloat(v String)

	GetLineHeight() TaggedDim
	SetLineHeight(v TaggedDim)

	GetPosition() BoolString
	SetPosition(v BoolString)

	GetTableLayout() String
	SetTableLayout(v String)

	GetTop() TaggedDim
	SetTop(v TaggedDim)

	GetVerticalAlign() TaggedDim
	SetVerticalAlign(v TaggedDim)

	GetVisibility() String
	SetVisibility(v String)

	GetBorderBottomLeftRadius() Point
	SetBorderBottomLeftRadius(v Point)

	GetBorderBottomRightRadius() Point
	SetBorderBottomRightRadius(v Point)

	GetBorderTopLeftRadius() Point
	SetBorderTopLeftRadius(v Point)

	GetBorderTopRightRadius() Point
	SetBorderTopRightRadius(v Point)

	GetColumnCount() IntString
	SetColumnCount(v IntString)

	GetColumnWidth() TaggedDim
	SetColumnWidth(v TaggedDim)

	GetFontFamily() Strings
	SetFontFamily(v Strings)

	GetFontFeatureSettings() FontFeatures
	SetFontFeatureSettings(v FontFeatures)

	GetFontKerning() String
	SetFontKerning(v String)

	GetFontLanguageOverride() String
	SetFontLanguageOverride(v String)

	GetFontSize() TaggedDim
	SetFontSize(v TaggedDim)

	GetFontStretch() String
	SetFontStretch(v String)

	GetFontStyle() String
	SetFontStyle(v String)

	GetFontVariantAlternates() String
	SetFontVariantAlternates(v String)

	GetFontVariantCaps() String
	SetFontVariantCaps(v String)

	GetFontVariantEastAsian() SStrings
	SetFontVariantEastAsian(v SStrings)

	GetFontVariantLigatures() SStrings
	SetFontVariantLigatures(v SStrings)

	GetFontVariantNumeric() SStrings
	SetFontVariantNumeric(v SStrings)

	GetFontVariantPosition() String
	SetFontVariantPosition(v String)

	GetFontWeight() IntString
	SetFontWeight(v IntString)

	GetFontVariationSettings() SFloatStrings
	SetFontVariationSettings(v SFloatStrings)

	GetHyphenateLimitZone() TaggedDim
	SetHyphenateLimitZone(v TaggedDim)

	GetHyphenateCharacter() String
	SetHyphenateCharacter(v String)

	GetHyphenateLimitChars() Limits
	SetHyphenateLimitChars(v Limits)

	GetHyphens() String
	SetHyphens(v String)

	GetLetterSpacing() TaggedDim
	SetLetterSpacing(v TaggedDim)

	GetTextAlignAll() String
	SetTextAlignAll(v String)

	GetTextAlignLast() String
	SetTextAlignLast(v String)

	GetTextIndent() TaggedDim
	SetTextIndent(v TaggedDim)

	GetTextTransform() String
	SetTextTransform(v String)

	GetWhiteSpace() String
	SetWhiteSpace(v String)

	GetWordBreak() String
	SetWordBreak(v String)

	GetWordSpacing() TaggedDim
	SetWordSpacing(v TaggedDim)

	GetTransform() Transforms
	SetTransform(v Transforms)

	GetContinue() String
	SetContinue(v String)

	GetMaxLines() TaggedInt
	SetMaxLines(v TaggedInt)

	GetOverflow() String
	SetOverflow(v String)

	GetOverflowWrap() String
	SetOverflowWrap(v String)

	GetCounterIncrement() SIntStrings
	SetCounterIncrement(v SIntStrings)

	GetCounterReset() SIntStrings
	SetCounterReset(v SIntStrings)

	GetCounterSet() SIntStrings
	SetCounterSet(v SIntStrings)

	GetAnchor() String
	SetAnchor(v String)

	GetLink() TaggedString
	SetLink(v TaggedString)

	GetLang() TaggedString
	SetLang(v TaggedString)

	GetBoxDecorationBreak() String
	SetBoxDecorationBreak(v String)

	GetBookmarkLabel() ContentProperties
	SetBookmarkLabel(v ContentProperties)

	GetBookmarkLevel() TaggedInt
	SetBookmarkLevel(v TaggedInt)

	GetBookmarkState() String
	SetBookmarkState(v String)

	GetContent() SContent
	SetContent(v SContent)

	GetStringSet() StringSet
	SetStringSet(v StringSet)

	GetImageOrientation() SBoolFloat
	SetImageOrientation(v SBoolFloat)

	GetPage() Page
	SetPage(v Page)

	GetAppearance() String
	SetAppearance(v String)

	GetOutlineColor() Color
	SetOutlineColor(v Color)

	GetOutlineStyle() String
	SetOutlineStyle(v String)

	GetOutlineWidth() TaggedDim
	SetOutlineWidth(v TaggedDim)

	GetBoxSizing() String
	SetBoxSizing(v String)

	GetBackgroundColor() Color
	SetBackgroundColor(v Color)

	GetBackgroundImage() Images
	SetBackgroundImage(v Images)

	GetBackgroundRepeat() Repeats
	SetBackgroundRepeat(v Repeats)

	GetBackgroundAttachment() Strings
	SetBackgroundAttachment(v Strings)

	GetBackgroundPosition() Centers
	SetBackgroundPosition(v Centers)

	GetBackgroundSize() Sizes
	SetBackgroundSize(v Sizes)

	GetBackgroundClip() Strings
	SetBackgroundClip(v Strings)

	GetBackgroundOrigin() Strings
	SetBackgroundOrigin(v Strings)

	GetBreakAfter() String
	SetBreakAfter(v String)

	GetBreakBefore() String
	SetBreakBefore(v String)

	GetBreakInside() String
	SetBreakInside(v String)

	GetTextDecorationLine() Decorations
	SetTextDecorationLine(v Decorations)

	GetTextDecorationColor() Color
	SetTextDecorationColor(v Color)

	GetTextDecorationStyle() String
	SetTextDecorationStyle(v String)

	GetTextDecorationThickness() TaggedDim
	SetTextDecorationThickness(v TaggedDim)

	GetTextUnderlineOffset() TaggedDim
	SetTextUnderlineOffset(v TaggedDim)

	GetGridAutoColumns() GridAuto
	SetGridAutoColumns(v GridAuto)

	GetGridAutoFlow() Strings
	SetGridAutoFlow(v Strings)

	GetGridAutoRows() GridAuto
	SetGridAutoRows(v GridAuto)

	GetGridTemplateColumns() GridTemplate
	SetGridTemplateColumns(v GridTemplate)

	GetGridTemplateRows() GridTemplate
	SetGridTemplateRows(v GridTemplate)

	GetGridTemplateAreas() GridTemplateAreas
	SetGridTemplateAreas(v GridTemplateAreas)

	GetGridRowStart() GridLine
	SetGridRowStart(v GridLine)

	GetGridColumnStart() GridLine
	SetGridColumnStart(v GridLine)

	GetGridRowEnd() GridLine
	SetGridRowEnd(v GridLine)

	GetGridColumnEnd() GridLine
	SetGridColumnEnd(v GridLine)

	GetAlignContent() JustifyOrAlign
	SetAlignContent(v JustifyOrAlign)

	GetAlignItems() JustifyOrAlign
	SetAlignItems(v JustifyOrAlign)

	GetAlignSelf() JustifyOrAlign
	SetAlignSelf(v JustifyOrAlign)

	GetFlexBasis() TaggedDim
	SetFlexBasis(v TaggedDim)

	GetFlexDirection() String
	SetFlexDirection(v String)

	GetFlexGrow() Float
	SetFlexGrow(v Float)

	GetFlexShrink() Float
	SetFlexShrink(v Float)

	GetFlexWrap() String
	SetFlexWrap(v String)

	GetJustifyContent() JustifyOrAlign
	SetJustifyContent(v JustifyOrAlign)

	GetJustifyItems() JustifyOrAlign
	SetJustifyItems(v JustifyOrAlign)

	GetJustifySelf() JustifyOrAlign
	SetJustifySelf(v JustifyOrAlign)

	GetOrder() Int
	SetOrder(v Int)

	GetColumnGap() TaggedDim
	SetColumnGap(v TaggedDim)

	GetRowGap() TaggedDim
	SetRowGap(v TaggedDim)

	GetBottom() TaggedDim
	SetBottom(v TaggedDim)

	GetCaptionSide() String
	SetCaptionSide(v String)

	GetClear() String
	SetClear(v String)

	GetClip() Values
	SetClip(v Values)

	GetEmptyCells() String
	SetEmptyCells(v String)

	GetLeft() TaggedDim
	SetLeft(v TaggedDim)

	GetRight() TaggedDim
	SetRight(v TaggedDim)

	GetListStyleImage() Image
	SetListStyleImage(v Image)

	GetListStylePosition() String
	SetListStylePosition(v String)

	GetListStyleType() CounterStyleID
	SetListStyleType(v CounterStyleID)

	GetTextOverflow() String
	SetTextOverflow(v String)

	GetBlockEllipsis() TaggedString
	SetBlockEllipsis(v TaggedString)

	GetBorderSpacing() Point
	SetBorderSpacing(v Point)

	GetTransformOrigin() Point
	SetTransformOrigin(v Point)

	GetFontVariant() String
	SetFontVariant(v String)

	GetMarginBreak() String
	SetMarginBreak(v String)

	GetOrphans() Int
	SetOrphans(v Int)

	GetWidows() Int
	SetWidows(v Int)

	GetFootnoteDisplay() String
	SetFootnoteDisplay(v String)

	GetFootnotePolicy() String
	SetFootnotePolicy(v String)

	GetQuotes() Quotes
	SetQuotes(v Quotes)

	GetImageResolution() TaggedDim
	SetImageResolution(v TaggedDim)

	GetImageRendering() String
	SetImageRendering(v String)

	GetColumnFill() String
	SetColumnFill(v String)

	GetColumnSpan() String
	SetColumnSpan(v String)

	GetColumnRuleColor() Color
	SetColumnRuleColor(v Color)

	GetSize() Point
	SetSize(v Point)

	GetBleedLeft() TaggedDim
	SetBleedLeft(v TaggedDim)

	GetBleedRight() TaggedDim
	SetBleedRight(v TaggedDim)

	GetBleedTop() TaggedDim
	SetBleedTop(v TaggedDim)

	GetBleedBottom() TaggedDim
	SetBleedBottom(v TaggedDim)

	GetMarks() Marks
	SetMarks(v Marks)

	GetUnicodeBidi() String
	SetUnicodeBidi(v String)

	GetZIndex() IntString
	SetZIndex(v IntString)

	GetOpacity() Float
	SetOpacity(v Float)

	GetColumnRuleStyle() String
	SetColumnRuleStyle(v String)

	GetColumnRuleWidth() TaggedDim
	SetColumnRuleWidth(v TaggedDim)

	GetBorderImageSlice() Values
	SetBorderImageSlice(v Values)

	GetBorderImageWidth() Values
	SetBorderImageWidth(v Values)

	GetBorderImageOutset() Values
	SetBorderImageOutset(v Values)

	GetBorderImageRepeat() Strings
	SetBorderImageRepeat(v Strings)

	GetMaskBorderSlice() Values
	SetMaskBorderSlice(v Values)

	GetMaskBorderWidth() Values
	SetMaskBorderWidth(v Values)

	GetMaskBorderOutset() Values
	SetMaskBorderOutset(v Values)

	GetMaskBorderRepeat() Strings
	SetMaskBorderRepeat(v Strings)

	GetMaskBorderMode() String
	SetMaskBorderMode(v String)

	GetObjectFit() String
	SetObjectFit(v String)

	GetObjectPosition() CenterPos
	SetObjectPosition(v CenterPos)
}

var propsNames = [...]string{
	PBorderBottomColor:       "border-bottom-color",
	PBorderBottomStyle:       "border-bottom-style",
	PBorderBottomWidth:       "border-bottom-width",
	PMarginBottom:            "margin-bottom",
	PPaddingBottom:           "padding-bottom",
	PBorderLeftColor:         "border-left-color",
	PBorderLeftStyle:         "border-left-style",
	PBorderLeftWidth:         "border-left-width",
	PMarginLeft:              "margin-left",
	PPaddingLeft:             "padding-left",
	PBorderRightColor:        "border-right-color",
	PBorderRightStyle:        "border-right-style",
	PBorderRightWidth:        "border-right-width",
	PMarginRight:             "margin-right",
	PPaddingRight:            "padding-right",
	PBorderTopColor:          "border-top-color",
	PBorderTopStyle:          "border-top-style",
	PBorderTopWidth:          "border-top-width",
	PMarginTop:               "margin-top",
	PPaddingTop:              "padding-top",
	PWidth:                   "width",
	PHeight:                  "height",
	PMinWidth:                "min-width",
	PMinHeight:               "min-height",
	PMaxWidth:                "max-width",
	PMaxHeight:               "max-height",
	PBorderCollapse:          "border-collapse",
	PTabSize:                 "tab-size",
	PBorderImageSource:       "border-image-source",
	PMaskBorderSource:        "mask-border-source",
	PColor:                   "color",
	PDirection:               "direction",
	PDisplay:                 "display",
	PFloat:                   "float",
	PLineHeight:              "line-height",
	PPosition:                "position",
	PTableLayout:             "table-layout",
	PTop:                     "top",
	PVerticalAlign:           "vertical-align",
	PVisibility:              "visibility",
	PBorderBottomLeftRadius:  "border-bottom-left-radius",
	PBorderBottomRightRadius: "border-bottom-right-radius",
	PBorderTopLeftRadius:     "border-top-left-radius",
	PBorderTopRightRadius:    "border-top-right-radius",
	PColumnCount:             "column-count",
	PColumnWidth:             "column-width",
	PFontFamily:              "font-family",
	PFontFeatureSettings:     "font-feature-settings",
	PFontKerning:             "font-kerning",
	PFontLanguageOverride:    "font-language-override",
	PFontSize:                "font-size",
	PFontStretch:             "font-stretch",
	PFontStyle:               "font-style",
	PFontVariantAlternates:   "font-variant-alternates",
	PFontVariantCaps:         "font-variant-caps",
	PFontVariantEastAsian:    "font-variant-east-asian",
	PFontVariantLigatures:    "font-variant-ligatures",
	PFontVariantNumeric:      "font-variant-numeric",
	PFontVariantPosition:     "font-variant-position",
	PFontWeight:              "font-weight",
	PFontVariationSettings:   "font-variation-settings",
	PHyphenateLimitZone:      "hyphenate-limit-zone",
	PHyphenateCharacter:      "hyphenate-character",
	PHyphenateLimitChars:     "hyphenate-limit-chars",
	PHyphens:                 "hyphens",
	PLetterSpacing:           "letter-spacing",
	PTextAlignAll:            "text-align-all",
	PTextAlignLast:           "text-align-last",
	PTextIndent:              "text-indent",
	PTextTransform:           "text-transform",
	PWhiteSpace:              "white-space",
	PWordBreak:               "word-break",
	PWordSpacing:             "word-spacing",
	PTransform:               "transform",
	PContinue:                "continue",
	PMaxLines:                "max-lines",
	POverflow:                "overflow",
	POverflowWrap:            "overflow-wrap",
	PCounterIncrement:        "counter-increment",
	PCounterReset:            "counter-reset",
	PCounterSet:              "counter-set",
	PAnchor:                  "anchor",
	PLink:                    "link",
	PLang:                    "lang",
	PBoxDecorationBreak:      "box-decoration-break",
	PBookmarkLabel:           "bookmark-label",
	PBookmarkLevel:           "bookmark-level",
	PBookmarkState:           "bookmark-state",
	PContent:                 "content",
	PStringSet:               "string-set",
	PImageOrientation:        "image-orientation",
	PPage:                    "page",
	PAppearance:              "appearance",
	POutlineColor:            "outline-color",
	POutlineStyle:            "outline-style",
	POutlineWidth:            "outline-width",
	PBoxSizing:               "box-sizing",
	PBackgroundColor:         "background-color",
	PBackgroundImage:         "background-image",
	PBackgroundRepeat:        "background-repeat",
	PBackgroundAttachment:    "background-attachment",
	PBackgroundPosition:      "background-position",
	PBackgroundSize:          "background-size",
	PBackgroundClip:          "background-clip",
	PBackgroundOrigin:        "background-origin",
	PBreakAfter:              "break-after",
	PBreakBefore:             "break-before",
	PBreakInside:             "break-inside",
	PTextDecorationLine:      "text-decoration-line",
	PTextDecorationColor:     "text-decoration-color",
	PTextDecorationStyle:     "text-decoration-style",
	PTextDecorationThickness: "text-decoration-thickness",
	PTextUnderlineOffset:     "text-underline-offset",
	PGridAutoColumns:         "grid-auto-columns",
	PGridAutoFlow:            "grid-auto-flow",
	PGridAutoRows:            "grid-auto-rows",
	PGridTemplateColumns:     "grid-template-columns",
	PGridTemplateRows:        "grid-template-rows",
	PGridTemplateAreas:       "grid-template-areas",
	PGridRowStart:            "grid-row-start",
	PGridColumnStart:         "grid-column-start",
	PGridRowEnd:              "grid-row-end",
	PGridColumnEnd:           "grid-column-end",
	PAlignContent:            "align-content",
	PAlignItems:              "align-items",
	PAlignSelf:               "align-self",
	PFlexBasis:               "flex-basis",
	PFlexDirection:           "flex-direction",
	PFlexGrow:                "flex-grow",
	PFlexShrink:              "flex-shrink",
	PFlexWrap:                "flex-wrap",
	PJustifyContent:          "justify-content",
	PJustifyItems:            "justify-items",
	PJustifySelf:             "justify-self",
	POrder:                   "order",
	PColumnGap:               "column-gap",
	PRowGap:                  "row-gap",
	PBottom:                  "bottom",
	PCaptionSide:             "caption-side",
	PClear:                   "clear",
	PClip:                    "clip",
	PEmptyCells:              "empty-cells",
	PLeft:                    "left",
	PRight:                   "right",
	PListStyleImage:          "list-style-image",
	PListStylePosition:       "list-style-position",
	PListStyleType:           "list-style-type",
	PTextOverflow:            "text-overflow",
	PBlockEllipsis:           "block-ellipsis",
	PBorderSpacing:           "border-spacing",
	PTransformOrigin:         "transform-origin",
	PFontVariant:             "font-variant",
	PMarginBreak:             "margin-break",
	POrphans:                 "orphans",
	PWidows:                  "widows",
	PFootnoteDisplay:         "footnote-display",
	PFootnotePolicy:          "footnote-policy",
	PQuotes:                  "quotes",
	PImageResolution:         "image-resolution",
	PImageRendering:          "image-rendering",
	PColumnFill:              "column-fill",
	PColumnSpan:              "column-span",
	PColumnRuleColor:         "column-rule-color",
	PSize:                    "size",
	PBleedLeft:               "bleed-left",
	PBleedRight:              "bleed-right",
	PBleedTop:                "bleed-top",
	PBleedBottom:             "bleed-bottom",
	PMarks:                   "marks",
	PUnicodeBidi:             "unicode-bidi",
	PZIndex:                  "z-index",
	POpacity:                 "opacity",
	PColumnRuleStyle:         "column-rule-style",
	PColumnRuleWidth:         "column-rule-width",
	PBorderImageSlice:        "border-image-slice",
	PBorderImageWidth:        "border-image-width",
	PBorderImageOutset:       "border-image-outset",
	PBorderImageRepeat:       "border-image-repeat",
	PMaskBorderSlice:         "mask-border-slice",
	PMaskBorderWidth:         "mask-border-width",
	PMaskBorderOutset:        "mask-border-outset",
	PMaskBorderRepeat:        "mask-border-repeat",
	PMaskBorderMode:          "mask-border-mode",
	PObjectFit:               "object-fit",
	PObjectPosition:          "object-position",
}

// PropsFromNames maps CSS property names to internal enum tags.
var PropsFromNames = map[string]KnownProp{
	"border-bottom-color":        PBorderBottomColor,
	"border-bottom-style":        PBorderBottomStyle,
	"border-bottom-width":        PBorderBottomWidth,
	"margin-bottom":              PMarginBottom,
	"padding-bottom":             PPaddingBottom,
	"border-left-color":          PBorderLeftColor,
	"border-left-style":          PBorderLeftStyle,
	"border-left-width":          PBorderLeftWidth,
	"margin-left":                PMarginLeft,
	"padding-left":               PPaddingLeft,
	"border-right-color":         PBorderRightColor,
	"border-right-style":         PBorderRightStyle,
	"border-right-width":         PBorderRightWidth,
	"margin-right":               PMarginRight,
	"padding-right":              PPaddingRight,
	"border-top-color":           PBorderTopColor,
	"border-top-style":           PBorderTopStyle,
	"border-top-width":           PBorderTopWidth,
	"margin-top":                 PMarginTop,
	"padding-top":                PPaddingTop,
	"width":                      PWidth,
	"height":                     PHeight,
	"min-width":                  PMinWidth,
	"min-height":                 PMinHeight,
	"max-width":                  PMaxWidth,
	"max-height":                 PMaxHeight,
	"border-collapse":            PBorderCollapse,
	"tab-size":                   PTabSize,
	"border-image-source":        PBorderImageSource,
	"mask-border-source":         PMaskBorderSource,
	"color":                      PColor,
	"direction":                  PDirection,
	"display":                    PDisplay,
	"float":                      PFloat,
	"line-height":                PLineHeight,
	"position":                   PPosition,
	"table-layout":               PTableLayout,
	"top":                        PTop,
	"vertical-align":             PVerticalAlign,
	"visibility":                 PVisibility,
	"border-bottom-left-radius":  PBorderBottomLeftRadius,
	"border-bottom-right-radius": PBorderBottomRightRadius,
	"border-top-left-radius":     PBorderTopLeftRadius,
	"border-top-right-radius":    PBorderTopRightRadius,
	"column-count":               PColumnCount,
	"column-width":               PColumnWidth,
	"font-family":                PFontFamily,
	"font-feature-settings":      PFontFeatureSettings,
	"font-kerning":               PFontKerning,
	"font-language-override":     PFontLanguageOverride,
	"font-size":                  PFontSize,
	"font-stretch":               PFontStretch,
	"font-style":                 PFontStyle,
	"font-variant-alternates":    PFontVariantAlternates,
	"font-variant-caps":          PFontVariantCaps,
	"font-variant-east-asian":    PFontVariantEastAsian,
	"font-variant-ligatures":     PFontVariantLigatures,
	"font-variant-numeric":       PFontVariantNumeric,
	"font-variant-position":      PFontVariantPosition,
	"font-weight":                PFontWeight,
	"font-variation-settings":    PFontVariationSettings,
	"hyphenate-limit-zone":       PHyphenateLimitZone,
	"hyphenate-character":        PHyphenateCharacter,
	"hyphenate-limit-chars":      PHyphenateLimitChars,
	"hyphens":                    PHyphens,
	"letter-spacing":             PLetterSpacing,
	"text-align-all":             PTextAlignAll,
	"text-align-last":            PTextAlignLast,
	"text-indent":                PTextIndent,
	"text-transform":             PTextTransform,
	"white-space":                PWhiteSpace,
	"word-break":                 PWordBreak,
	"word-spacing":               PWordSpacing,
	"transform":                  PTransform,
	"continue":                   PContinue,
	"max-lines":                  PMaxLines,
	"overflow":                   POverflow,
	"overflow-wrap":              POverflowWrap,
	"counter-increment":          PCounterIncrement,
	"counter-reset":              PCounterReset,
	"counter-set":                PCounterSet,
	"anchor":                     PAnchor,
	"link":                       PLink,
	"lang":                       PLang,
	"box-decoration-break":       PBoxDecorationBreak,
	"bookmark-label":             PBookmarkLabel,
	"bookmark-level":             PBookmarkLevel,
	"bookmark-state":             PBookmarkState,
	"content":                    PContent,
	"string-set":                 PStringSet,
	"image-orientation":          PImageOrientation,
	"page":                       PPage,
	"appearance":                 PAppearance,
	"outline-color":              POutlineColor,
	"outline-style":              POutlineStyle,
	"outline-width":              POutlineWidth,
	"box-sizing":                 PBoxSizing,
	"background-color":           PBackgroundColor,
	"background-image":           PBackgroundImage,
	"background-repeat":          PBackgroundRepeat,
	"background-attachment":      PBackgroundAttachment,
	"background-position":        PBackgroundPosition,
	"background-size":            PBackgroundSize,
	"background-clip":            PBackgroundClip,
	"background-origin":          PBackgroundOrigin,
	"break-after":                PBreakAfter,
	"break-before":               PBreakBefore,
	"break-inside":               PBreakInside,
	"text-decoration-line":       PTextDecorationLine,
	"text-decoration-color":      PTextDecorationColor,
	"text-decoration-style":      PTextDecorationStyle,
	"text-decoration-thickness":  PTextDecorationThickness,
	"text-underline-offset":      PTextUnderlineOffset,
	"grid-auto-columns":          PGridAutoColumns,
	"grid-auto-flow":             PGridAutoFlow,
	"grid-auto-rows":             PGridAutoRows,
	"grid-template-columns":      PGridTemplateColumns,
	"grid-template-rows":         PGridTemplateRows,
	"grid-template-areas":        PGridTemplateAreas,
	"grid-row-start":             PGridRowStart,
	"grid-column-start":          PGridColumnStart,
	"grid-row-end":               PGridRowEnd,
	"grid-column-end":            PGridColumnEnd,
	"align-content":              PAlignContent,
	"align-items":                PAlignItems,
	"align-self":                 PAlignSelf,
	"flex-basis":                 PFlexBasis,
	"flex-direction":             PFlexDirection,
	"flex-grow":                  PFlexGrow,
	"flex-shrink":                PFlexShrink,
	"flex-wrap":                  PFlexWrap,
	"justify-content":            PJustifyContent,
	"justify-items":              PJustifyItems,
	"justify-self":               PJustifySelf,
	"order":                      POrder,
	"column-gap":                 PColumnGap,
	"row-gap":                    PRowGap,
	"bottom":                     PBottom,
	"caption-side":               PCaptionSide,
	"clear":                      PClear,
	"clip":                       PClip,
	"empty-cells":                PEmptyCells,
	"left":                       PLeft,
	"right":                      PRight,
	"list-style-image":           PListStyleImage,
	"list-style-position":        PListStylePosition,
	"list-style-type":            PListStyleType,
	"text-overflow":              PTextOverflow,
	"block-ellipsis":             PBlockEllipsis,
	"border-spacing":             PBorderSpacing,
	"transform-origin":           PTransformOrigin,
	"font-variant":               PFontVariant,
	"margin-break":               PMarginBreak,
	"orphans":                    POrphans,
	"widows":                     PWidows,
	"footnote-display":           PFootnoteDisplay,
	"footnote-policy":            PFootnotePolicy,
	"quotes":                     PQuotes,
	"image-resolution":           PImageResolution,
	"image-rendering":            PImageRendering,
	"column-fill":                PColumnFill,
	"column-span":                PColumnSpan,
	"column-rule-color":          PColumnRuleColor,
	"size":                       PSize,
	"bleed-left":                 PBleedLeft,
	"bleed-right":                PBleedRight,
	"bleed-top":                  PBleedTop,
	"bleed-bottom":               PBleedBottom,
	"marks":                      PMarks,
	"unicode-bidi":               PUnicodeBidi,
	"z-index":                    PZIndex,
	"opacity":                    POpacity,
	"column-rule-style":          PColumnRuleStyle,
	"column-rule-width":          PColumnRuleWidth,
	"border-image-slice":         PBorderImageSlice,
	"border-image-width":         PBorderImageWidth,
	"border-image-outset":        PBorderImageOutset,
	"border-image-repeat":        PBorderImageRepeat,
	"mask-border-slice":          PMaskBorderSlice,
	"mask-border-width":          PMaskBorderWidth,
	"mask-border-outset":         PMaskBorderOutset,
	"mask-border-repeat":         PMaskBorderRepeat,
	"mask-border-mode":           PMaskBorderMode,
	"object-fit":                 PObjectFit,
	"object-position":            PObjectPosition,
}
